@baseUrl = http://localhost:9001/api


### Register a new user
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "username": "rudaba",
  "password": "rudaba456",
  "firstName": "rudaba",
  "lastName": "kamor",
  "email": "rudaba@test.com",
  "phone": "123123123"
}

###

# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

# {
#   "username": "harrypotter",
#   "password": "harry123"
# }

# {
#   "username": "johnmcclane",
#   "password": "john123"
# }

{
  "username": "ellenripley",
  "password": "ellen123"
}


###

@authToken = {{login.response.body.token}}

### Get user details
GET {{baseUrl}}/users/2
Authorization: basic {{authToken}}

### Edit user details
PUT {{baseUrl}}/users/3
Content-Type: application/json
Authorization: basic {{authToken}}

{
  "firstName": "rudaba adnin",
  "phone": "456456456"
}

### List all users
GET {{baseUrl}}/users
Content-Type: application/json
Authorization: basic {{authToken}}

### Delete user
DELETE {{baseUrl}}/users/2
Content-Type: application/json
Authorization: basic {{authToken}}


### Change user password
PUT {{baseUrl}}/users/change-password
Content-Type: application/json
Authorization: basic {{authToken}}

{
  "oldPassword": "rudaba456",
  "newPassword": "rudaba123"
}

###

# @name logout
POST {{baseUrl}}/auth/logout
Content-Type: application/json
Authorization: basic {{authToken}}

#####################################

### Create a profile for a user
POST {{baseUrl}}/profiles
Content-Type: application/json
Authorization: basic {{authToken}}

{
  "githubProfile": "https://github.com/nayeem-mehedi",
  "otherProfile": "https://www.linkedin.com/in/nayeem-mehedi",
  "profilePicture": "https://example.com/profile.jpg",
  "userId": 3
}

### Get Self profile details
GET {{baseUrl}}/profiles/self
Authorization: basic {{authToken}}

###

### Get profile details
GET {{baseUrl}}/profiles/5
Authorization: basic {{authToken}}

###

### Update profile details
PUT {{baseUrl}}/profiles/3
Content-Type: application/json
Authorization: basic {{authToken}}

{
  "githubProfile": "https://github.com/nayeem-mehedi",
  "otherProfile": "https://www.linkedin.com/in/nayeem-mehedi",
  "profilePicture": "https://ui-avatars.com/api/?name=N+M"
}

# {
#   "githubProfile": "https://github.com/johndoe",
#   "otherProfile": "https://linkedin.com/in/johndoe_new",
#   "profilePicture": "https://ui-avatars.com/api/?name=N+M"
# }

###

### Update profile details - SELF
PUT http://localhost:9001/api/profiles/self
Content-Type: application/json
Authorization: basic {{authToken}}

{
  "githubProfile": "https://github.com/nayeem-mehedi",
  "otherProfile": "https://www.linkedin.com/in/nayeem-mehedi",
  "profilePicture": "https://ui-avatars.com/api/?name=N+M"
}

### Create a new skill
POST {{baseUrl}}/skills
Content-Type: application/json
Authorization: basic {{authToken}}

{
  "name": "Selenium222"
}

### List all skills
GET {{baseUrl}}/skills
Authorization: basic {{authToken}}

### Delete a skill
DELETE {{baseUrl}}/skills/110
Authorization: basic {{authToken}}

### Add skill to profile
POST {{baseUrl}}/profile-skills
Content-Type: application/json
Authorization: basic {{authToken}}

{
  "skills": [1, 100]
}

### Remove skill from profile
DELETE {{baseUrl}}/profile-skills/5
Authorization: basic {{authToken}}

###################################################

# @name search

GET {{baseUrl}}/search/user?query=Selenium&page=1&limit=10
Authorization: basic {{authToken}}

####

# @name search_project
# GET {{baseUrl}}/search/project?query=&page=1&limit=10&skills=JavaScript,React&topics=web,backend&contributor=&owner="
GET {{baseUrl}}/search/project?query=dev&page=1&limit=10&skills=Java&topics=web backend&contributor=&owner="
Authorization: basic {{authToken}}


#####

### List all topics
GET {{baseUrl}}/topics
Authorization: basic {{authToken}}

####

### List all topics
GET {{baseUrl}}/topics
Authorization: basic {{authToken}}

####

### Create topic
POST {{baseUrl}}/topics
Content-Type: application/json
Authorization: basic {{authToken}}

{
  "name": "Business"
}

####

### Delete topic
DELETE {{baseUrl}}/topics/22
Authorization: basic {{authToken}}

####

### List all projects
GET {{baseUrl}}/projects
Authorization: basic {{authToken}}

####

### List one project's details
GET {{baseUrl}}/projects/11
Authorization: basic {{authToken}}

####

### Create project
POST {{baseUrl}}/projects
Content-Type: application/json
Authorization: basic {{authToken}}

{
  "name": "Business",
  "description": "This is a business project.",
  "sourceCodeLink": "https://github.com/example/business-project",
  "topic": {
    "id": 1
  },
  "skills": [
    { "id": 1 },
    { "id": 2 }
  ],
  "users": [
    { "id": 1 },
    { "id": 2 }
  ]
}

####


### Update project
PUT {{baseUrl}}/projects/11
Content-Type: application/json
Authorization: basic {{authToken}}

{
  "name": "The Business News",
  "description": "A business New Site.",
  "sourceCodeLink": "https://github.com/example/tbs",
  "topic": {
    "id": 2
  },
  "skills": [
    { "id": 1 },
    { "id": 2 },
    { "id": 5 }
  ],
  "users": [
    { "id": 1 }
  ]
}

####

### Delete projects
DELETE {{baseUrl}}/projects/11
Authorization: basic {{authToken}}

####

##### PHASE 3 START #####

### List announcements for a user
GET {{baseUrl}}/announcements/user/2
Content-Type: application/json
Authorization: basic {{authToken}}

###


### Create an announcement for a user (self)
POST {{baseUrl}}/announcements/user
Content-Type: application/json
Authorization: basic {{authToken}}

{
  "title": "Test User Announcement 2",
  "content": "Checking if that is working!"
}

###

### List announcements for a project
GET {{baseUrl}}/announcements/project/1
Content-Type: application/json
Authorization: basic {{authToken}}

###

### Create an announcement for a project
POST {{baseUrl}}/announcements/project
Content-Type: application/json
Authorization: basic {{authToken}}

{
  "title": "Project Kickoff",
  "content": "The project has started",
  "projectId": "7"
}

###

### List notifications
GET {{baseUrl}}/notifications
Authorization: basic {{authToken}}

###

### Get notification count
GET {{baseUrl}}/notifications/count
Authorization: basic {{authToken}}

###

### Get notification details
GET {{baseUrl}}/notifications/770
Authorization: basic {{authToken}}

###

### Follow a user
GET {{baseUrl}}/follow/user/5
Authorization: basic {{authToken}}

###

### Follow a project
GET {{baseUrl}}/follow/project/10
Authorization: basic {{authToken}}

###

### List follow details
GET {{baseUrl}}/follow/list
Authorization: basic {{authToken}}

###

##### PHASE 3 END #####