# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main","frontend-main","server-setup"]
  pull_request:
    branches: [ "main","frontend-main","server-setup"]

jobs:
  build-frontend-main:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies for frontend
        working-directory: frontend
        run: npm install

      - name: Build frontend
        working-directory: frontend
        run: npm run build

  build-server-setp:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [18.x]
  
      steps:
        - name: checkout repo
          uses: actions/checkout@v4
  
        - name: setup node
          uses: actions/setup-node@v3
          with:
            node-version: '18'
  
        - name: Install dependencies for backend
          working-directory: backend
          run: npm install
  
        - name: Build frontend
          working-directory: backend
          run: npm run build
  
